feat: better error message when barcode length differs from expected
fulcrumgenomics/fqtk pull request #44
Opened 2024-07-09 16:25 UTC by TimD1

- fixes #31, error message is now more clear

2024-07-09 17:01 UTC, msto commented on src/lib/barcode_matching.rs
> +            "Sample barcode length ({}) differs from expected ({}) during barcode matching",
Would it be helpful to additionally include the sequence of the barcode in question?

2024-07-09 17:09 UTC, nh13 commented on src/lib/barcode_matching.rs
> +            "Sample barcode length ({}) differs from expected ({}) during barcode matching",
I think we want to know which _sample_ this is caused by, as well as the barcode bases (actual and expected) along with the length.

2024-07-09 17:30 UTC, TimD1 commented on src/lib/barcode_matching.rs
> +            "Sample barcode length ({}) differs from expected ({}) during barcode matching",
Sounds good. I can add that info if I replace `BarcodeMatcher.sample_barcodes` with `BarcodeMatcher.samples` (vector of `Sample` structs storing `sample_id`s and `barcode`s). It looks like this was the eventual plan anyways: https://github.com/fulcrumgenomics/fqtk/blob/33925525a79dfb8cc1ca23ba78e6c2f0e59eda42/src/lib/barcode_matching.rs#L25-L27

2024-07-10 21:18 UTC, TimD1 commented
This is my first time writing Rust, so please feel free to make suggestions for better style/design/etc.

A note on the new tests:
Since `Sample`s do not allow empty barcodes:
https://github.com/fulcrumgenomics/fqtk/blob/6ed98a3334eb13f22dd8054d39d9b8f77e76b337/src/lib/samples.rs#L48-L50

My understanding is that `new()` is the only way to get a new `Sample` outside of the `samples.rs` module, since `Sample` contains a private field (`ordinal`). Therefore, I dropped the test for `BarcodeMatcher` being initialized with a `Sample` with an empty barcode:
https://github.com/fulcrumgenomics/fqtk/blob/6ed98a3334eb13f22dd8054d39d9b8f77e76b337/src/lib/barcode_matching.rs#L178-L185

And modified the test that allowed empty barcodes to be compared to check that it now fails.
https://github.com/fulcrumgenomics/fqtk/blob/6ed98a3334eb13f22dd8054d39d9b8f77e76b337/src/lib/barcode_matching.rs#L195-L198

2025-02-13 00:03 UTC, nh13 requested changes
One minor question

2025-02-13 00:03 UTC, nh13 commented on src/lib/barcode_matching.rs
> +        }
Shall we make a clone of the sample instead of modifying them?

2025-02-18 20:28 UTC, TimD1 commented on src/lib/barcode_matching.rs
> +        }
I think `to_vec()` should already create a copy of `samples`: https://doc.rust-lang.org/std/primitive.slice.html#method.to_vec

I just rebased and pushed my changes.

2025-02-18 20:50 UTC, nh13 approved these changes
Thanks @TimD1 !

2025-02-18 20:50 UTC, merged